### ISSUE TITLE
Usage info seems incorrect

### ISSUE THREAD

**Issue by dtoubelis** [saltstack-formulas/salt-cloud-reactor#3]
It seems that usage info in README file is incorrect. I looked through the code and I think it should look something like this:

``` yaml
reactor:
  - 'salt/cloud/*/cache_node_new':
    - '/srv/reactor/autoscale.sls'
  - 'salt/cloud/*/cache_node_diff':
    - '/srv/reactor/autoscale.sls'

nova.autoscale:
  provider: rackspace-dfw
  ssh_username: root
```
